version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - flasknet

  web:
    build: ./app
    container_name: flask_web
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flasknet

networks:
  flasknet:

volumes:
  db_data:
